### ISSUE TITLE
Configurable width

### ISSUE THREAD

**Issue by rvagg** [filecoin-project/go-amt-ipld#29]
The width provides the primary tuneable parameter, allowing for a selection along the block-size, mutation cost and traversal cost spectrums. A fixed width of 8 provides for a maximum arity of 8 which. It's also something that probably should be benchmarked to understand the true costs involved but we can't do that without the ability to change it. Some `Bmap` code in here suggests that variability was a TODO, but a single byte is the easy case and that's taken advantage of here, hence the 8.

**Comment by Stebalien** [comment]
Fixed.
