### ISSUE TITLE
Optimize diffing performance

### ISSUE THREAD

**Issue by strahe** [filecoin-project/go-amt-ipld#69]
Hi, 

Is there a plan to optimize diffing performance?

refer to: https://github.com/ipfs/go-merkledag/blob/master/dagutils/diff.go#L104

**Comment by Stebalien** [comment]
https://github.com/filecoin-project/go-amt-ipld/blob/master/diff.go?

**Comment by frrist** [comment]
@strahe there is also https://github.com/filecoin-project/go-amt-ipld/blob/master/diff_parallel.go which operates similar to the link from Stebalien but in parallel.
